### ISSUE TITLE
Potential new fields

### ISSUE THREAD

**Issue by lomereiter** [METASPACE2020/metadata#2]
Judging from dataset names on `alpha.metasp.eu`, it could be a good idea to add some of the following as optional fields:
* pixel size
* acquisition date
* matrix concentration

**Comment by andy-d-palmer** [comment]
agreed that additional info could be useful
 - pixel size *should* be in the imzml so hopefully we can scrape it (can this be done in-browser and autofilled?)
 - acquisition date. Probably don't need it. I see it only for datasets we have uploaded (and it's mostly because I'm too lazy to format a better dataset name)
- matrix concentration. yeah. more detail on sample prep could be really useful but because of all the different technology it's hard to standardise the metadata form without making it a hassle to fill in. I'll have a think

**Comment by lomereiter** [comment]
Another suggestion: add 'university abbreviation' field that we can show in the tables or other places with limited amount of space; enforce it to be ≤ 15–20 characters long; in forms, autopopulate it from the database, to new submitters suggest to use twitter aliases if possible. (e.g. UniMelb instead of UoMelbourne we currently have)

**Comment by theodev** [comment]
+Upvote

**Comment by andy-d-palmer** [comment]
Now the institute is a separate field in the table the need for an abbreviation isn't so high as we don't need to prepend it to the dataset name.
